site_name: Мой статический сайт
site_description: Сайт, созданный для задания
site_author: Данил

theme:
  name: null
  custom_dir: theme

nav:
  - Главная: index.md
  - О проекте: about.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
